version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt/app
  postgres:
    image: "postgres"
    environment: 
      - POSTGRES_USER=aisi
      - POSTGRES_PASSWORD=aisi
      - POSTGRES_DB=aisi_notes
    ports:
      - '5433:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql # copy the sql script to create tables
      - ./scripts/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql # copy the sql script to fill tables
volumes:
  database-data: